description = "Ubuntu bionic base image with buildpacks for Java, .NET Core, NodeJS, Go, Python, PHP, Ruby, Apache HTTPD, NGINX and Procfile"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/dotnet-core:0.6.0"
  version = "0.6.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/go:0.10.0"
  version = "0.10.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/httpd:0.1.1"
  version = "0.1.1"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java-native-image:5.8.0"
  version = "5.8.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java:5.15.0"
  version = "5.15.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nginx:0.3.3"
  version = "0.3.3"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nodejs:0.8.0"
  version = "0.8.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/php:0.5.5"
  version = "0.5.5"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:4.3.1"
  version = "4.3.1"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/python:0.8.1"
  version = "0.8.1"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/ruby:0.9.0"
  version = "0.9.0"

[lifecycle]
  version = "0.11.4"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ruby"
    version = "0.9.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core"
    version = "0.6.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "0.8.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go"
    version = "0.10.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/python"
    version = "0.8.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/php"
    version = "0.5.5"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "0.3.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.1.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "5.8.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "5.15.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "4.3.1"

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.2.38-full-cnb"
  id = "io.buildpacks.stacks.bionic"
  run-image = "index.docker.io/paketobuildpacks/run:full-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:full-cnb"]
