description = "Ubuntu bionic base image with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.11.4"

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.2.31-full-cnb"
  id = "io.buildpacks.stacks.bionic"
  run-image = "index.docker.io/paketobuildpacks/run:full-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:full-cnb"]
