name: Push Builder Image

on:
  release:
    types:
    - published

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:

    - name: Parse Event
      id: event
      run: |
        echo "::set-output name=tag::$(jq -r '.release.tag_name' "${GITHUB_EVENT_PATH}" | sed s/^v//)"

    - name: Checkout
      uses: actions/checkout@v2

    # Use :latest image when we have confidence in latest releases
    # Current latest (0.14.0) has a runtime error
    - name: Install Pack
      run: |
        id=$(docker create buildpacksio/pack:0.14.0)
        sudo docker cp $id:/layers/paketo-buildpacks_go-build/targets/bin/pack /usr/local/bin/
        docker rm -v $id

    - name: Create Builder Image
      run: |
        pack create-builder builder-tmp --config builder.toml

    - name: Push
      env:
        GCR_PUSH_BOT_JSON_KEY: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
      run: |
        echo "${GCR_PUSH_BOT_JSON_KEY}" | docker login --username _json_key --password-stdin gcr.io
        docker tag builder-tmp "gcr.io/paketo-buildpacks/builder-tmp:full"
        docker tag builder-tmp "gcr.io/paketo-buildpacks/builder-tmp:latest"
        docker tag builder-tmp "gcr.io/paketo-buildpacks/builder-tmp:${{ steps.event.outputs.tag }}-full"

        docker push "gcr.io/paketo-buildpacks/builder-tmp:full"
        docker push "gcr.io/paketo-buildpacks/builder-tmp:latest"
        docker push "gcr.io/paketo-buildpacks/builder-tmp:${{ steps.event.outputs.tag }}-full"
